### ISSUE TITLE
Prepare DeezyMatch tutorial, LinkedPasts

### ISSUE THREAD

**Issue by kasra-hosseini** [Living-with-machines/DeezyMatch#79]
Ideas:
- [x] Run tutorials via Binder
- [ ] Release model/datasets

**Comment by kmcdono2** [comment]
@kasra-hosseini et al do we need any introductory prose about the utility of DeezyMatch that goes beyond the current abstract/paper text? If so, happy to start thinking about this next week.

In the mean time @mcollardanuy if you need help with preparing the abstract to submit for Linked Pasts just say the word. Is there a google doc where I can add potential participants? Once the abstract is ready, we could email Bruno Martins and Paty Murrieta Flores about offering comment on the two aspects e.g. matching and gaz construction.

**Comment by mcollardanuy** [comment]
I haven't done anything on this yet, I was planning to work on this on Thursday afternoon. But here's the new (empty) doc: https://docs.google.com/document/d/1kUJhoestVYged5gXfxS0fHeqZHkT_A1Q0pWnI_NRUs8/edit

**Comment by kasra-hosseini** [comment]
> @kasra-hosseini et al do we need any introductory prose about the utility of DeezyMatch that goes beyond the current abstract/paper text? If so, happy to start thinking about this next week.

- We tried to cover most of DeezyMatch utilities in the abstract/paper. What do you think @mcollardanuy @fedenanni ? Maybe we can also mention that the length of the input strings can be changed (although it has not been tested on any realistic dataset)?

**Comment by kasra-hosseini** [comment]
Add the link to the HackMD file here once it is ready. That file can be used to capture comments from the participants. @mcollardanuy @fedenanni @kmcdono2  What do you think? We can then either ask participants to make issues directly on the repo (preferred) or add them to the HackMD file.
