### ISSUE TITLE
Input file for inference/candidate ranking

### ISSUE THREAD

**Issue by kasra-hosseini** [Living-with-machines/DeezyMatch#84]
@mcollardanuy Wrote:

Currently DeezyMatch requires this input for the candidates and query files:

```
Mach Loop	0	false
North Wick	0	false
Trawden	0	false
Mugswell	0	false
```

You get an error if one of the columns is missing, but the second and third columns are actually dummy columns in the inference step.

It would make it more user-friendly if the user could just input a file that has one string per line, as in:

```
Mach Loop
North Wick
Trawden
Mugswell
```

**Comment by kasra-hosseini** [comment]
@mcollardanuy I think this is already addressed in the new version?

**Comment by mcollardanuy** [comment]
It is, thank you!
