### ISSUE TITLE
Change package dependencies from == to >= 

### ISSUE THREAD

**Issue by fedenanni** [Living-with-machines/DeezyMatch#95]
This is to avoid incompatibilities between DeezyMatch and other libraries (see for instance torch in [DeezyMatch](https://github.com/Living-with-machines/DeezyMatch/blob/master/requirements.txt) and in [sentence-transformers](https://github.com/UKPLab/sentence-transformers/blob/master/requirements.txt))

**Comment by mcollardanuy** [comment]
I think we can close this issue, right?

**Comment by fedenanni** [comment]
Yes it was solved in #96
