### ISSUE TITLE
Fix ranking metric documentation in candidateRanker

### ISSUE THREAD

**Issue by mcollardanuy** [Living-with-machines/DeezyMatch#97]
Check lines 328-331 in `candidateRanker.py` (see [here](https://github.com/Living-with-machines/DeezyMatch/blob/06f80171cf36543ce6941c960c2d89366fb03fab/DeezyMatch/candidateRanker.py#L328)). Comment and code are not aligned: according to the comment, 0.99 is multiplied, but in the code it's 1.01. Change the comment accordingly:

```python
elif ranking_metric.lower() in ["cosine"]:
  # 0.99 is multiplied to avoid issues with float numbers and rounding errors
  if query_candidate_pd["cosine_dist"].max() > (selection_threshold*1.01):
     break 
```

**Comment by kasra-hosseini** [comment]
Done https://github.com/Living-with-machines/DeezyMatch/pull/121
